sudo: false
language: node_js
node_js:
  - "7"

cache:
  yarn: true
  directories:
    - test/elm-stuff
    - elm-stuff
    - node_modules

install:
  - yarn install
  - elm package install --yes
  - mkdir -p build

script:
  - yarn elm-test
  - yarn elm-make -- src/Main.elm --output build/elm.js
  - yarn uglifyjs -- build/elm.js -o build/elm.min.js
  - yarn uglifyjs -- src/index.js -o build/index.min.js
  - cp src/prod.html build.index.html

deploy:
  provider: gcs
  access_key_id:
    secure: "DeC+iJvvU7erPV9f2wMl5khpZVgK2coGP/4VmB3blfKAnK1DFpzKtMiOvYlgallzAy5nfY9ETQYQm47GS3YodijIr4V609+5j1VE7r6b/h1J91tksKohrkJPmvGjEJgbp1BW2XjexnzTET3S5LcgBMlUOUITb7sBE7UQGY8S3bI75lK13hQHExQKybLdTaoATgWen2okDddhTrKNGvLbMF2amuF4d179MD3ztshmtf7e9aEFHKpVbWh0ZaZIcFqtIPrPbx1BFiJ13oDIdZ8JqEkYwiJmT9znocIGBkgWKdjnfZawpMMTnbWazNdNwvYscEXSonMTHpM86r5adMp0lJdHtgHAW10+DV+tDJ+Poy1vLKrw9Gx0wNFpLwxrst4pDphEbr8ePOJ2EWItiuQW03rgFXBZSFgmWsW6U2AjdHNMZKylc1MvlNaL3MOdmcDmK6mxsAau6lMFZPxVhPOkIlHi1VGb0OPCj42+haCu05rkDbLdvyGDU+O1SdjWxZFj3tK1kXDPi5sLLI+6b+bQ5hIIHcrC7yMiVDO/G4HrXDo8m8y7FEWtKuwQFaEwhdJlCRjTWP3C5M0BWtYiBbcV8MEeIKSY19g4I7PEPBrY3CdPLq+DVGGmUi16Vz8OuJ6Hxie4lpJ0i5FL8NL15LPKWrBzWgSXqe9CcuZI0c7/cAE="
  secret_access_key:
    secure: "ofDzU0GOV1oz1oRJwh6Kzui7E7HwxgmF3ImPwo0KyJ+9mHxuZWg/jRVvDrIw1L6SeGLHvH5dkHtImdezpe4Yuy4Wd5PVW/dvD9A4jCf7irU7BzLuDTRxL92xfhayeh+Uv07PGqeZnA5f7gDKw600TgHMlwP2x02c3p9fkYKm2J7OBdHxmx+VQrx05KyEPdJWdjP7l8rYyyJty83wb1++lDGqGuQLTg2eq5fjXTb2VL9Kx/+rzpcX2XJqm87WQljy/cwc2Q6CCeflcH7CsNnk/tqQLsp9500xO2fiSNYHuO4UdOOyfwgYkWn3uGvG0qFhpUcw+6+jREHUvZF6MkjJz33eyL4RtqThAEFmm1Jf3qOEmRcPDCh0BWTbqrwNJzyvUN92sn+lWh35FN56TVXOBWIgVHpKElO5nWbgJc7IYYofHi3ptKM3UY5GeuzoY3tu3o8VzoPFihPWuLZq5AvTFpbeVLL2lkLkkgyd8nR3DRGmUYZIJfpsh+T7Q6xsgIolLBQjJTVsELbAx+2tu1U/4rAzhoqIlOp0PqE/HDg4s7c2iuORxqYc8aHKbp97Lt71+MuZYyFVAij5m5CPHYmBK//DQktYfd3DCvEhw0uooAKzS0X83b/UeOmRyKPmVPi1qcRfMJu6PRCAvd7EfLFdKCED7jjsgi2/r++8eBSaz10="
  bucket: "trellooverviewhosting"
  skip_cleanup: true
  acl: public-read
  local_dir: build
  detect_encoding: true
  cache_control: "max-age=3600"
  on:
    branch: master
    repo: mattiaslundberg/trellooverview
