sudo: false
language: node_js

cache:
  yarn: true
  directories:
    - test/elm-stuff/build-artifacts
    - elm-stuff
    - node_modules

install:
  - yarn install
  - elm package install --yes

script:
  - yarn elm-test
